Patient Portal - My profile tab
lk-gov-health-hiu/project-nhdx pull request #30
Opened 2024-01-11 04:45 UTC by mrxnn

resolves #28 

![NEHR Client Application](https://github.com/lk-gov-health-hiu/project-nhdx/assets/21257657/0f0f226d-8415-4542-a8e6-43b7405bba1e)

2024-01-17 06:12 UTC, janithRS commented on nehr-patient-portal/modules/my-profile.tsx
> +                          <CalendarIcon className="ml-auto h-4 w-4 opacity-50" />
Please use react-icons/fa. `<FaCalendarAlt />`

2024-01-17 06:14 UTC, janithRS commented on nehr-patient-portal/modules/my-profile.tsx
> +                      <Calendar
AFAIK there is an issue with the shadcn calendar component: if you need to select a date from 1996 you need to go back month by month. I think it's OK to use the default input date picker for this. WDYT?

2024-01-17 12:04 UTC, mrxnn commented on nehr-patient-portal/modules/my-profile.tsx
> +                      <Calendar
I didn't know this issue existed. I replaced it with the default input date picker.

2024-01-17 12:06 UTC, mrxnn commented on nehr-patient-portal/modules/my-profile.tsx
> +                          <CalendarIcon className="ml-auto h-4 w-4 opacity-50" />
No longer using the calendar input

2024-01-23 16:50 UTC, janithRS requested changes

2024-01-23 16:50 UTC, janithRS commented on nehr-patient-portal/modules/my-profile.tsx
> +const Heading = ({ children }: { children: any }) => {
Shall we this to components?

2024-01-23 16:50 UTC, janithRS commented on nehr-patient-portal/tailwind.config.js
> -}
EOF

2024-01-23 16:50 UTC, janithRS commented on nehr-patient-portal/modules/my-profile.tsx
> +const Heading = ({ children }: { children: any }) => {
Also, it's better to have a defined prop interface in case we need to expand the header props later.

2024-01-23 17:11 UTC, mrxnn commented on nehr-patient-portal/modules/my-profile.tsx
> +const Heading = ({ children }: { children: any }) => {
Moved

2024-01-23 17:56 UTC, janithRS approved these changes

2024-02-15 08:35 UTC, closed without merging